#!/bin/bash

output=assets
mkdir -p $output

big() {
convert \
  -size 2403x1296\
  "xc:rgb(39,89,39)"\
  -font Transuranium\
  -pointsize $size\
  -fill "rgba(214,130,53,90)"\
  -gravity center\
  -annotate 0 $y miff:- |\
convert miff:- \
  \(\
    +clone\
    +level-colors GREY50\
    -process "attenuate 6"\
    -rotate -1\
    +noise Poisson\
    -colorspace Gray\
  \)\
  -compose Overlay\
  -composite miff:- |\
convert miff:- \
  \(\
    -size 1x5\!\
    xc:white\
    +noise Poisson\
    -level 40,60%\
    -colorspace Gray\
    -scale 10x25\!\
    -rotate -2\
    -scale 50x80\!\
    -blur 30\
    -scale 200x200\!\
    -blur 30\
    -scale 2403x1296\!\
    -rotate 1\
  \)\
  -compose Overlay\
  -composite \
  -crop 1920x1080\!+240+108\
 big/timeout-$y.png

  convert big/timeout-$y.png -blur 15 big/success-$y.jpg
}

for (( x = $1; x < $2; x++ )); do
  y=`printf "%03d" $x`
  brightness=$[ ( $RANDOM % 10 ) + 10 ]

  backR=$[ $brightness * 10 / 100 ]
  backG=$[ $brightness * 186 / 100 ]
  backB=$[ $brightness * 181 / 100 ]

  size=$[ ( $RANDOM % 100 ) + 700 ]
  offsetX=$[ ( $RANDOM % 50 ) + 100 + $size / 4 ]
  offsetY=$[ ( $RANDOM % 50 ) + 600 + $size / 3]
  textX=$[ ( $RANDOM % 200 ) + $offsetX - 100 ]
  textY=$[ ( $RANDOM % 50 ) + $offsetY ]
  texture=$[ ( $RANDOM % 12 ) + 1 ]

  expanded=`printf "%03d" $3`
  convert -size 1920x1080 "xc:rgb(119,97,119)" -font Helvetica -pointsize $size -fill "rgba(182,103,182)" -gravity center -annotate $(( 5 - x / 10 )) $y -depth 4 $output/$expanded-purple-$y.png

  convert -size 1920x1080 "xc:rgb(76,75,129)" -font Helvetica -pointsize $size -fill "rgba(112,120,167)" -gravity center -annotate $(( -3 + x / 8 )) $y -depth 4 $output/$expanded-azure-$y.png

  convert -size 1920x1080 "xc:rgb(119,69,67)" -font Helvetica -pointsize $size -fill "rgba(182,105,102)" -gravity center -annotate $(( -6 + x / 11 )) $y -depth 4 $output/$expanded-red-$y.png

  convert -size 1920x1080 "xc:rgb(97,119,99)" -font Helvetica -pointsize $size -fill "rgba(103,182,110)" -gravity center -annotate $(( -2 + x / 4 )) $y -depth 4 $output/$expanded-green-$y.png


done
