#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

die() {
  echo $*
  exit
}

list() {
  curl -s waivescreen.com/api/screens | python -mjson.tool
}

connect() {
  ssh-keygen -f "/home/chris/.ssh/known_hosts" -R "[reflect.waivescreen.com]:$1"
  ssh -XC -i $DIR/../../Linux/keys/ScreenAccess adorno@reflect.waivescreen.com -p $1
  exit
}

reload() {
  LOCK=/tmp/sync-screen
  if [[ -e $LOCK ]] ; then
    echo "Woops, not running with $LOCK existing ($( stat -c %y $LOCK )). Are you already running this?"
    exit -1
  fi

  touch $LOCK

  pkill osd_cat

  echo "Sync: "$(( $( date +%s ) - $( cat /tmp/last-sync ) )) \
    | osd_cat \
      -c white -S darkgray -s 2 -o 10 -d 30 \
      -f lucidasanstypewriter-bold-24 &

  ssh screen "./reload"

  rm $LOCK
}

# To get power management working, setthe following up in bios
#
# Advanced ▷ LPSS & SCC Configuration ▷ OS Selection ▷ Android
#
restart() {
  ssh screen "sudo reboot"&
}

for i in $*; do
  case $1 in
    list) list ;;
    patch) 
      curl http://waivescreen.com/patchfile > /tmp/patch || die "Can't find waivescreen.com"
      git apply /tmp/patch || die "Can't apply /tmp/patch"
      ;;
    connect) connect $2 ;;
    sync|reload) reload ;;
    on) on.js ;;
    off) off.js ;;
    force) $DIR/pcycle.js ;;
    restart|reboot|reset|pcycle) restart ;;
    *) 
      echo -e "Error: $1\nValid: patch sync|reload list off connect on restart|reboot"
      [[ $# -gt "1" ]] && echo "Exit: Found unknown command. Ending parsing"
      exit
      ;;
  esac

  shift
done
