#!/bin/bash

export HOME=/root
export PATH=$PATH:/bin:/usr/bin:/sbin:/usr/sbin

# This permits us to know how many times we've booted.
# It allows us to (or not to) trust values in our db
if [ ! -e /etc/bootcount ]; then
  echo "1" > /etc/bootcount
  chmod 0444 /etc/bootcount
else
  echo $(( $(cat /etc/bootcount) + 1 )) > /etc/bootcount
fi

# I think this kills the modem
# powertop --auto-tune

XINITRC=/root/.xinitrc /usr/bin/xinit &
