#!/bin/bash
 
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

. $DIR/baseline.sh

if ! declare -f $1 > /dev/null; then
  . $DIR/lib.sh
fi

if ! declare -f $1 > /dev/null; then
  echo "Woops, $1 is not defined"
  list
  exit 1
fi

eval $* 
