#!/usr/bin/perl

use strict;
use warnings;
use Scalar::Util qw/reftype/;

my $home = '/home/adorno/';

sub install_list {
  my $ix = 0;
  open(my $fh, '<:encoding(UTF-8)', "$home/WaiveScreen/Linux/fai-config/package_config/DEBIAN") or die '';

  my @all = qw//;
  while (my $row = <$fh>) {
    chomp $row;

    # Remove comments
    $row =~ s/#.*//ig;

    # Skip empty lines
    next if $row =~ /^$/;

    # Only use the first set
    if ( $row =~ /^PACKAGES/ ) {
      last if $ix++ == 1;

    } else {
      push(@all, split(/\s+/, $row));
    }
  }
  qx(sudo rm -f /tmp/to-install /tmp/already-installed);
  open(my $fhout, '>', '/tmp/to-install');
  print $fhout join "\n", sort(@all);
  close $fhout;
  qx(dpkg-query -l | grep '^ii'| awk '{ print \$2 }' | sort > /tmp/already-installed);
  return qx(comm -13 /tmp/already-installed /tmp/to-install);
}

sub capture_all_cameras {
  my @videoList = glob("/dev/video*");

  for(my $ix = 0; $ix < $#videoList; $ix += 2) {
    unlink "/tmp/video${ix}.mp4";
    qx(ffmpeg -i /dev/video$ix -an -t 5 -y /tmp/video${ix}.mp4 &);
  }
  sleep 8;

  my @outlist = glob("/tmp/video*.mp4");

  return $#outlist;
}

sub acceptance_screen {
  my $out= qx($home/WaiveScreen/ScreenDaemon/dcall kv_get | sed -E s"/[\'=;]/ /"g);
  my %values;
  my $uptime = qx(awk ' { print \$1 } ' /proc/uptime);
  my $version = qx(cd $home/WaiveScreen && git describe);
  my @all = eval "qw($out)";
  for(my $ix = 0; $ix < $#all; $ix += 2) {
    $values{$all[$ix]} = $all[$ix + 1];
  }

  open(my $html, '>', '/tmp/acceptance.html');
  print $html qq(<style>
  html{font-size:150%}
.bad,.good,.value {
  color:rgb(170,64,64);
  font-weight: bold;
}
.value { color:rgb(64,64,64);margin-left:2rem }
.good { color:rgb(64,170,64); }
.good:before,.bad:before {
  content: '\\2714';
  font-size: 2rem;
  width: 1rem;
  margin-right:0.25rem;
  vertical-align: sub;
}
#header { font-weight: bold; margin-bottom:.5rem }
.bad:before { content: '\\2717'; }
</style>
<body style="text-align:center;padding:1rem;background:url('file://$home/WaiveScreen/tools/client/test-bg.gif') repeat">
<span style="box-shadow:0 0 1px 1px black;padding:1rem;display:inline-block;background:rgb(255,255,255);font-family:sans-serif;font-size:1.5rem;min-width:20rem;text-align:left">
<div id='header'>
  <div >$values{'uuid'}</div>
  <div style=font-weight:normal;font-size:1.25rem>$values{'number'} <span style="margin:.2rem 0;float:right;font-size:0.85rem">$version</span></div>
</div>
  );

  my @features = detect_features();
  my @top = ();
  my @bottom = ();
  for (my $ix = 0; $ix < scalar @features; $ix += 2) {
    my $key = $features[$ix];
    my $value = $features[$ix + 1];
    if (!$value || $value <= 1) {
      my $class = $value ? 'good' : 'bad';
      push @top, "<div class=$class>$key</div>";
    } else {
      push @bottom, "<div class=value>$key: $value</div>";
    }
  }
  print $html join "\n", @top;
  print $html join "\n", @bottom;

  print $html qq(
  <div style=padding-top:1rem;font-size:1rem>
    <div style=font-size:.9rem;font-weight:bold>up: $uptime | boot: $values{'runcount'} <br/><script>
    document.write(("" + new Date()).split('\(').join('<br>\('));</script></div>
  </div>
  <div style=padding-top:.5rem;font-size:1rem;font-style:italic;text-align:center>press ctrl+w to exit</div>
</body>
  );
  close $html;
}

# see #73
sub detect_features {
  my @videoList = glob("/dev/video*");
  my $hasSim = qx(mmcli -m 0 --output-keyvalue | grep sim | grep org | wc -l);

  # * btle - todo
  my @features = (
    "modem", -e "/dev/cdc-wdm0" ? 1 : 0,
    "arduino", -e "/dev/ttyACM0" ? 1 : 0,
    "cameras", ($#videoList + 1) / 2,
    "ip", qx(mmcli -b 0| grep address | wc -l) > 0,
    "wifi", -e "/proc/sys/net/ipv4/conf/wlp1s0" ? 1 : 0,
    "sim", $hasSim
  );
  for (my $ix = 1; $ix < scalar @features; $ix += 2) {
    $features[$ix] =~ s/\s//g;
  }
  return @features;
}

sub acceptance_test {
  my %results = {
    # Make sure gps has actual lat/lng
    'gps' => qx(mmcli -m 0 --location-get --output-keyvalue | grep longitude | grep -v -- -- | wc -l),

    # Check to make sure we have access to sensors
    'sensor' => qx(pycall sensor_last | wc -c) > 200,

    # Make sure we can get online-- todo
    
    # Number of cameras/bus isolation
    'cameras' => capture_all_cameras
  };
}

if ($#ARGV >= 0) {
 my $res = eval "${ARGV[0]}()";
 if (ref $res eq ref {}) {
   print "hash";
 } else {
   print $res;
 }
}
