#!/usr/bin/python3
import lib.lib as lib
import sys

if len(sys.argv) > 1:
    eval("lib." + sys.argv[1] + "()")
else:
    print("I need an argument")
    [print(" {}".format(x)) for x in sorted(list(set(dir(lib)) - set(dir())))]
    sys.exit(-1)
