#!/bin/bash

base=/home/adorno/WaiveScreen

$base/ScreenDaemon/dcall set_autobright
$base/tools/client/sanity-check.sh
$base/ScreenDaemon/dcall ping

# Essentially any asset that hasn't shown in 3 days is purged.
find /var/cache/assets -mtime +3 -type f -exec rm {} \;

touch /tmp/last_cron
