#!/bin/bash

/home/adorno/WaiveScreen/ScreenDaemon/dcall set_autobright
/home/adorno/WaiveScreen/tools/client/sanity-check.sh

# Essentially any asset that hasn't shown in 3 days is purged.
find -mtime +3 -type f /var/cache/assets -exec rm {} \;

touch /tmp/last_cron
