#!/bin/bash

CP="cp -pvu"
USER=adorno

USERID=1000
CHDEST=/home/$USER
DEST=$FAI_ROOT$CHDEST

cp -vuTr --preserve=mode,timestamps ../files/home $DEST
chmod 0600 $DEST/.ssh/KeyBounce $DEST/.ssh/github $DEST/.ssh/dev
chown -R $USERID.$USERID $DEST

for path in /var/cache/assets /var/log/screen /var/db /var/log; do
  [ -e $FAI_ROOT$path ] || mkdir -p $FAI_ROOT$path
  chmod 0777 $FAI_ROOT$path
done

# xinit is going to be for root's home
mv ../files/home/.xinitrc $FAI_ROOT/root

# The overly user-hostile version of sudo needs to be fixed
ainsl /etc/sudoers "$USER ALL=NOPASSWD: ALL" "$USER"

# The retarded bell in bash to do nothing on tab complete needs to go
sed -i '/^# set bell-style none/s/^# //' $FAI_ROOT/etc/inputrc

# The stupid smarmy "plan your install" crap needs to go
[ -e $FAI_ROOT/etc/motd ] && rm -f $FAI_ROOT/etc/motd   

cpfile() {
  $CP "../files"$1 $FAI_ROOT$1
}

# A bunch of stupid modules shouldn't be loaded.
for i in /etc/modprobe.d/blacklist.conf /etc/udev/rules.d/45-arduino.rules /etc/logrotate.d/screen.log; do
  cpfile $i
done

$ROOTCMD chown root.root /etc/logrotate.d/screen.log

ainsl -a /etc/modprobe.d/blacklist.conf 'blacklist pcspkr'

# This allows a dev mount
ainsl /etc/fuse.conf "^user_allow_other"

# Gives the user perms for arduino
ainsl /etc/group "dialout:x:20:adorno"
ainsl /etc/group- "dialout:x:20:adorno"

# Make sure the paths from the lib are shared to the shell
ainsl $CHDEST/.bashrc 'source $HOME/const.sh' 'const.sh'
$ROOTCMD $CHDEST/dcall get_uuid
$ROOTCMD $CHDEST/dcall pip_install

fcopy -ivm root,root,0755 /etc/cron.hourly/autobright
fcopy -ivM /etc/polkit-1/localauthority/50-local.d/modemmanager.pkla
fcopy -ivM /etc/dhcp/dhcpd.conf
