#!/bin/bash

CP="cp -pvu"
USER=adorno

# This is predictable
USERID=1000
CHDEST=/home/$USER
DEST=$FAI_ROOT$CHDEST

[ -e $DEST/.env ] && cp -p $DEST/.env $DEST/.env-saveme
cp -vuTr --preserve=mode,timestamps ../files/home $DEST
chmod 0600 $DEST/.ssh/KeyBounce $DEST/.ssh/github $DEST/.ssh/dev
[ -e $DEST/.env-saveme ] && mv $DEST/.env-saveme $DEST/.env
chown -R $USERID.$USERID $DEST

# This is to allow non-root users to get the modem info (and
# everything else, but let's ignore that)
#
# TODO: This doesn't fix it ... I don't know why
sed -i 's/auth_self_keep/yes/g' $FAI_ROOT/usr/share/polkit-1/actions/org.freedesktop.ModemManager1.policy 

if [ ! -e $DEST/assets ] ; then
  # This is a cache for assets in case we go offline
  mkdir $DEST/assets
  chmod 0777 $DEST/assets
fi

# Allow any user to create a logfile.
chmod 0777 $FAI_ROOT/var/log

# This shouldn't be necessary, but permissions seem to
# want to just snap back after the above thing is done.
touch $FAI_ROOT/var/log/screendaemon.log
$ROOTCMD chown $USERID.$USERID /var/log/screendaemon.log

# xinit is going to be at a root level
$CP ../files/home/.xinitrc $FAI_ROOT/root
rm $DEST/.xinitrc

# The overly user-hostile version of sudo needs to be fixed
ainsl /etc/sudoers "$USER ALL=NOPASSWD: ALL" "$USER"

# The retarded default bell thing in bash to do nothing
# on tab complete needs to go
sed -i '/^# set bell-style none/s/^# //' $FAI_ROOT/etc/inputrc

# This stupid smarmy "plan your install" crap needs to go.
[ -e $FAI_ROOT/etc/motd ] && rm -f $FAI_ROOT/etc/motd   

cpfile() {

  if [ ! -e "../files"$1 ]; then
    echo "FAILURE! CANNOT FIND $1"
  else
    echo "Copying $1"
  fi

  $CP "../files"$1 $FAI_ROOT$1
}

# A bunch of stupid modules shouldn't be loaded.
cpfile /etc/modprobe.d/blacklist.conf
cpfile /etc/udev/rules.d/45-arduino.rules
cpfile /etc/logrotate.d/screen.log

ainsl -a /etc/modprobe.d/blacklist.conf 'blacklist pcspkr'

# This allows a dev mount
ainsl /etc/fuse.conf "^user_allow_other"

for path in /var/log/screen /var/db/; do
  mkdir -p $FAI_ROOT$path
  chmod 0777 $FAI_ROOT$path
done

# Swap may be needed for ACPI
#sed -i '/swap/d' /etc/fstab

# apt purge -y rpcbind

# Gives the user perms for arduino
ainsl /etc/group "dialout:x:20:adorno"
ainsl /etc/group- "dialout:x:20:adorno"

# $ROOTCMD chsh -s /bin/bash $USER

# Optimize the screen for power
#powertop --auto-tune --debug

$ROOTCMD pip3 install $CHDEST/pip/*

# Make sure the paths from the lib are shared to the shell
ainsl $CHDEST/.bashrc 'source $HOME/const.sh' 'const.sh'
$ROOTCMD $CHDEST/dcall uuid

ainsl /etc/hosts "127.0.0.1 debian"
