#!/bin/sh
git() {
  ssh screen "cd WaiveScreen;git pull"
}

reload() {
  LOCK=/tmp/sync-screen
  if [ -e $LOCK ] ; then
    echo "Woops, not running with $LOCK existing ($( stat -c %y $LOCK )). Are you already running this?"
    exit -1
  fi

  touch $LOCK

  pkill osd_cat

  echo "Sync: "$(( $( date +%s ) - $( cat /tmp/last-sync ) )) \
    | osd_cat \
      -c white \
      -S darkgray \
      -s 2 \
      -o 10 \
      -d 30 \
      -f lucidasanstypewriter-bold-24 &

  ssh screen "./reload"

  rm $LOCK
}

# This was a version of restart before we
# got power management working, which
# we do by setting the following up in bios
#
# Advanced ▷ LPSS & SCC Configuration ▷ OS Selection ▷ Android
#
oldrestart() {
  restart
  sshpid=$!
  for i in `seq 3 -1 1`; do
    sleep 1
    echo -n "$i..."
  done
  kill $sshpid
  pcycle
}

restart() {
  ssh screen "sudo reboot"&
}

for i in $*; do
  case $1 in
    git) git ;;
    sync|reload) reload ;;
    on) on.js ;;
    off) off.js ;;
    force) pcycle ;;
    restart|reboot|reset|pcycle) restart ;;
    *) 
      echo "Error: $1\nValid: git reload off on restart"
      if [ $# -gt "1" ]; then
        echo "Exit: Found unknown command. Ending parsing"
      fi
      exit
      ;;
  esac

  shift
done
