#!/bin/sh
git() {
  ssh screen "cd WaiveScreen;git pull"
}

reload() {
  ssh screen "./reload"
}

restart() {
  ssh screen "sudo reboot"
  for i in `seq 1 4`; do
    sleep 1
    echo -n "$i... "
  done
  pcycle
}

for i in $*; do
  case $1 in
    git) git ;;
    reload) reload ;;
    on) on.js ;;
    off) off.js ;;
    restart|reboot|pcycle) restart ;;
    *) echo "git reload off on restart"
  esac

  shift
done
