#!/bin/sh
git() {
  ssh screen "cd WaiveScreen;git pull"
}

reload() {
  ssh screen "./reload"
}

case $1 in
  git) git ;;
  reload) reload ;;
  on) on.js ;;
  off) off.js ;;
  restart|reboot|pcycle) pcycle ;;
  *) echo "git reload off on restart"
esac
